name: lastfm_dashboard
description: Last.fm Dashboard

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev.12 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  rxdart: ^0.23.1
  synchronized: ^2.2.0
  path_provider: ^1.5.1
  charts_flutter: ^0.9.0
  shared_preferences: ^0.5.6+1
  sembast_web: ^1.0.0
  cupertino_icons: ^0.1.2
  provider: ^4.1.0-dev+3
  sqflite: ^1.3.0
  random_string: ^2.0.1
  collection: ^1.14.12
  quiver: ^2.1.3

dev_dependencies:
  sqflite_common_ffi: ^1.0.0+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700